# Generated by Django 4.1.7 on 2023-04-02 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
                ('slug', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('Image', models.FileField(blank=True, null=True, upload_to='files/images/LandingPage/photos/Image/%Y/%m/%d/')),
                ('ImageName', models.CharField(blank=True, max_length=300, null=True)),
                ('slideImage', models.FileField(blank=True, null=True, upload_to='files/images/LandingPage/photos/slideImage/%Y/%m/%d/')),
                ('Title', models.CharField(max_length=100)),
                ('Description', models.CharField(blank=True, max_length=500, null=True)),
                ('price', models.CharField(blank=True, max_length=100, null=True)),
                ('discount', models.CharField(blank=True, max_length=100, null=True)),
                ('DoctorImage', models.FileField(blank=True, null=True, upload_to='files/images/Doctors/photos/%Y/%m/%d/')),
                ('DoctorName', models.CharField(blank=True, max_length=300, null=True)),
                ('Doctorjobtitle', models.CharField(blank=True, max_length=300, null=True)),
                ('DoctorDescription', models.CharField(blank=True, max_length=300, null=True)),
                ('QuestionsTitle', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('servicesproperty_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='LandingPage.servicesproperty')),
            ],
            bases=('LandingPage.servicesproperty',),
        ),
        migrations.CreateModel(
            name='LandingPageReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.FileField(blank=True, null=True, upload_to='files/images/LandingPageReviews/photos/Image/%Y/%m/%d/')),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('lndingPageReviews', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Reviews', to='LandingPage.landingpage')),
            ],
        ),
        migrations.CreateModel(
            name='LandingPageQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=300, null=True)),
                ('answer', models.CharField(blank=True, max_length=300, null=True)),
                ('lndingPageQuestions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='LandingPage.landingpage')),
            ],
        ),
        migrations.CreateModel(
            name='LandingPagePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, max_length=100, null=True)),
                ('lndingPagePrice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Price', to='LandingPage.landingpage')),
            ],
        ),
        migrations.CreateModel(
            name='LandingPageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.FileField(blank=True, null=True, upload_to='files/images/LandingPageImage/photos/Image/%Y/%m/%d/')),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('lndingPageImage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='LandingPage.landingpage')),
            ],
        ),
        migrations.CreateModel(
            name='LandingPageDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titel', models.CharField(blank=True, max_length=100, null=True)),
                ('Description', models.CharField(blank=True, max_length=500, null=True)),
                ('lndingPageDescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='description', to='LandingPage.landingpage')),
            ],
        ),
        migrations.CreateModel(
            name='LandingPageBeforeAfter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, max_length=100, null=True)),
                ('Description', models.CharField(blank=True, max_length=500, null=True)),
                ('Image', models.FileField(blank=True, null=True, upload_to='files/images/LandingPageBeforeAfter/photos/Image/%Y/%m/%d/')),
                ('lndingPageBeforeAfter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beforeafter', to='LandingPage.landingpage')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('knew', models.CharField(choices=[('كيف عرفتنا', 'كيف عرفتنا'), ('تأمين', 'تأمين'), ('صديق ', 'صديق '), ('أسرة', 'أسرة'), ('الجيران', 'الجيران'), ('جوجل ', 'جوجل '), ('واتساب', 'واتساب'), ('سناب', 'سناب'), ('انستقرام', 'انستقرام'), ('تويتر', 'تويتر'), ('فيس بوك ', 'فيس بوك '), ('تيك توك', 'تيك توك'), ('يوتيوب ', 'يوتيوب '), ('البريد الإلكتروني', 'البريد الإلكتروني'), ('موقع', ' موقع الإلكتروني'), ('آخر', 'آخر')], default='كيف عرفتنا', max_length=50)),
                ('Message', models.CharField(max_length=500)),
                ('STATUS', models.CharField(choices=[('انتظار', 'انتظار'), ('حجز غير مؤكد', 'حجز غير مؤكد'), ('حجز مؤكد', 'حجز مؤكد'), ('إلغاءحجزه', 'إلغاءحجزه'), ('حضر', 'حضر')], default='انتظار', max_length=50)),
                ('landingPage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LandingPage.landingpage')),
            ],
        ),
    ]
