# Generated by Django 4.1.7 on 2023-04-02 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicesproperty',
            name='slug',
        ),
    ]
