# Generated by Django 4.1.7 on 2023-04-02 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0003_servicesproperty_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicesproperty',
            options={'ordering': ('-created_at',)},
        ),
    ]
