# Generated by Django 4.1.7 on 2023-04-02 13:21

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Image', models.FileField(blank=True, null=True, upload_to='files/images/Story/Image/%Y/%m/%d/')),
                ('Title', models.CharField(blank=True, max_length=100, null=True)),
                ('Description', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='youtubeStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video_id', models.CharField(blank=True, max_length=300, null=True)),
                ('Title', models.CharField(blank=True, max_length=100, null=True)),
                ('Description', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
    ]
