# Generated by Django 4.1.7 on 2023-04-02 13:21

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageBeforeAfter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Image', models.FileField(blank=True, null=True, upload_to='files/images/Home/ImageBeforeAfter/Image/%Y/%m/%d/')),
                ('ImageName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LOGO', models.FileField(blank=True, null=True, upload_to='files/images/Home/Information/Image/%Y/%m/%d/')),
                ('FaviconIco', models.FileField(blank=True, null=True, upload_to='files/images/Home/Information/Image/%Y/%m/%d/')),
                ('WebName', models.CharField(blank=True, max_length=300, null=True)),
                ('Copyright', models.CharField(blank=True, max_length=300, null=True)),
                ('PHONE', models.CharField(blank=True, max_length=300, null=True)),
                ('Twitterlinke', models.CharField(blank=True, max_length=500, null=True)),
                ('instagramlinke', models.CharField(blank=True, max_length=500, null=True)),
                ('facebooklinke', models.CharField(blank=True, max_length=500, null=True)),
                ('Youtubelinke', models.CharField(blank=True, max_length=500, null=True)),
                ('linkedinlinke', models.CharField(blank=True, max_length=500, null=True)),
                ('Whatsapp', models.CharField(blank=True, max_length=500, null=True)),
                ('snapchat', models.CharField(blank=True, max_length=500, null=True)),
                ('Address', models.CharField(blank=True, max_length=500, null=True)),
                ('OpeningHours', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('question', models.CharField(blank=True, max_length=500, null=True)),
                ('answer', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WebImage', models.FileField(blank=True, null=True, upload_to='files/images/Home/Slide/Image/%Y/%m/%d/')),
                ('MobilImage', models.FileField(blank=True, null=True, upload_to='files/images/Home/Slide/Image/%Y/%m/%d/')),
                ('Title', models.CharField(blank=True, max_length=100, null=True)),
                ('Description', models.CharField(blank=True, max_length=300, null=True)),
                ('video_id', models.CharField(blank=True, max_length=100, null=True)),
                ('questionImage', models.FileField(blank=True, null=True, upload_to='files/images/Home/Slide/Image/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='youtubeBeforeAfter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('VideoName', models.CharField(blank=True, max_length=100, null=True)),
                ('video_id', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
