# Generated by Django 4.1.7 on 2023-04-02 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagebeforeafter',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='youtubebeforeafter',
            options={'ordering': ('-created_at',)},
        ),
    ]
