# Generated by Django 4.1.7 on 2023-04-02 13:21

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ourmessage', models.CharField(max_length=300, null=True)),
                ('Ourvision', models.CharField(max_length=300, null=True)),
                ('rateus', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AboutDR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.FileField(blank=True, null=True, upload_to='files/images/About/Image/%Y/%m/%d/')),
                ('Title', models.CharField(max_length=300, null=True)),
                ('Description', models.CharField(max_length=300, null=True)),
                ('Spotlight', models.CharField(max_length=300, null=True)),
                ('SpotlightDescription', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clinicphotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='files/images/About/Image/%Y/%m/%d/')),
                ('imagename', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionsAndAnswersPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
                ('question', models.CharField(max_length=300, null=True)),
                ('answer', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.FileField(blank=True, null=True, upload_to='files/images/About/photos/Image/%Y/%m/%d/')),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='specifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=300, null=True)),
                ('Image', models.FileField(blank=True, null=True, upload_to='files/images/About/Image/%Y/%m/%d/')),
                ('Title1', models.CharField(max_length=300, null=True)),
                ('Description1', models.CharField(max_length=300, null=True)),
                ('Title2', models.CharField(max_length=300, null=True)),
                ('Description2', models.CharField(max_length=300, null=True)),
                ('Title3', models.CharField(max_length=300, null=True)),
                ('Description3', models.CharField(max_length=300, null=True)),
            ],
        ),
    ]
